version: "3.3"
services:
  nginx:
    image: danday74/nginx-lua
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/nginx/conf/nginx.conf
      - ./app:/app
    environment:
      PHP: "php:9000"
    links:
      - php
  php:
    depends_on:
      - db
    links:
      - db
    build: .
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASS: password
      DB_NAME: app
  db:
    ports:
      - "3306:3306"
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - ./schema:/schema
    restart: always
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: username
      MYSQL_PASSWORD: password
volumes:
  db: {}
